/**
 * RasdNewsTemplate.tsx
 *
 * Remotion video template for the "عاجل وسط نص" (Breaking News Center Text) layout.
 *
 * ── Config compatibility ──────────────────────────────────────────────────────
 * This template is designed to produce output visually consistent with the
 * static images generated by news_image_lib (Python/Skia). It does so by:
 *
 *  1. Accepting the raw `layout_config.layers` JSON from the template config
 *     and reading all positions, sizes, font paths, and style params from it
 *     (no hardcoded pixel values).
 *
 *  2. Performing the same binary-search font-fit via `useArabicTextFit` hook
 *     (mirrors LayoutEngine._fit_text_to_box).
 *
 *  3. Applying Kashida (tatweel U+0640) justification to non-last lines via
 *     `kashidaJustifyLine` (mirrors ArabicTextHandler.kashida_justify_line).
 *
 *  4. Using the same line-height formula:
 *     - use_metrics_line_spacing=true  → fontBoundingBox × lineSpacing
 *     - use_metrics_line_spacing=false → fontSize × lineSpacing
 *
 * See `arabicUtils.ts` and `hooks/useArabicTextFit.ts` for implementation.
 * See `.agents/skills/arabic-video-text/SKILL.md` for agent guidelines.
 */

import React from "react";
import {
  AbsoluteFill,
  Img,
  OffthreadVideo,
  interpolate,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
import { loadFont } from "@remotion/fonts";
import { useArabicTextFit } from "./hooks/useArabicTextFit";

// ─── Arabic fonts (Ghroob Arabic) ────────────────────────────────────────────
loadFont({
  family: "GhroobArabic",
  url: staticFile("fonts/GhroobArabicitf-Bold.otf"),
  weight: "700",
  format: "opentype",
});
loadFont({
  family: "GhroobArabic",
  url: staticFile("fonts/GhroobArabicitf-Light.otf"),
  weight: "300",
  format: "opentype",
});

// ─── Types ────────────────────────────────────────────────────────────────────

/** Style block from a news_image_lib text layer config */
export type TextLayerStyle = {
  align?: "left" | "center" | "right";
  color?: string;
  kashida?: boolean;
  direction?: "rtl" | "ltr";
  font_family?: string;
  line_spacing?: number;
  min_font_size?: number;
  base_font_size?: number;
  vertical_align?: "top" | "center" | "bottom";
  use_metrics_line_spacing?: boolean;
  text_background?: {
    enabled?: boolean;
    box_color?: string;
    box_opacity?: number;
    padding_x?: number;
    padding_y?: number;
    corner_radius?: number;
    line_gap?: number;
    text_alignment?: string;
  };
};

/** A text layer from the template JSON layout_config */
export type TextLayerConfig = {
  id: string;
  type: "text";
  x: number;
  y: number;
  width: number;
  max_height: number;
  content?: string; // static default, overridden by dynamic content prop
  style: TextLayerStyle;
  object_key?: string;
  object_type?: string;
};

export type RasdQuoteItem = {
  text: string;
  fadeInStart: number;
  fullyVisibleStart: number;
  fadeOutStart: number;
  hiddenAt: number;
  loopFadeInStart?: number;
};

export type RasdNewsProps = {
  /** Path (staticFile) or URL of the photo/video clip shown in the upper area. */
  photoSrc: string;
  /** Whether the photoSrc is a video (OffthreadVideo) or image (Img). */
  photoIsVideo?: boolean;
  /** Path (staticFile) or URL of the template background image (panel + badge baked in). */
  backgroundImageSrc: string;
  /** The headline quotes to cycle through. */
  quotes: RasdQuoteItem[];
  /** Small label in the bottom-right of the red panel (e.g. source name). */
  sourceText: string;
  /**
   * Raw text layer config from layout_config.layers for the main news headline.
   * When provided, all positioning, sizing, and style params come from this config.
   * When omitted, legacy defaults are used.
   */
  newsTextLayer?: TextLayerConfig;
  /**
   * Raw text layer config from layout_config.layers for the source text.
   */
  sourceTextLayer?: TextLayerConfig;
};

// ─── Legacy defaults (1080 × 1440 canvas) ────────────────────────────────────
// These match the "عاجل وسط نص4" template JSON exactly.

const DEFAULT_NEWS_TEXT_LAYER: TextLayerConfig = {
  id: "text_default_news",
  type: "text",
  x: 526,
  y: 900,
  width: 908,
  max_height: 383,
  style: {
    align: "right",
    color: "#FFFFFF",
    kashida: true,
    direction: "rtl",
    font_family: "GhroobArabic",
    line_spacing: 0.9,
    min_font_size: 50,
    base_font_size: 150,
    vertical_align: "top",
    use_metrics_line_spacing: true,
  },
};

const DEFAULT_SOURCE_TEXT_LAYER: TextLayerConfig = {
  id: "text_default_source",
  type: "text",
  x: 858,
  y: 1370,
  width: 206,
  max_height: 47,
  style: {
    align: "right",
    color: "#FFFFFF",
    kashida: false,
    direction: "rtl",
    font_family: "GhroobArabic",
    line_spacing: 1.2,
    min_font_size: 30,
    base_font_size: 80,
    vertical_align: "center",
    use_metrics_line_spacing: false,
  },
};

const DEFAULT_QUOTES: RasdQuoteItem[] = [
  {
    text: "ترامب لفوكس نيوز: سنصبح حماة مضيق هرمز وربما نطلق على أنفسنا لقب الملاك الحارس للمضيق",
    fadeInStart: 0,
    fullyVisibleStart: 0,
    fadeOutStart: 108,
    hiddenAt: 120,
    loopFadeInStart: 623,
  },
  {
    text: "ترامب لفوكس نيوز: كنا نحرس مضيق هرمز دون مقابل أما الآن فسنحرسه ونحصل على مقابل لذلك",
    fadeInStart: 135,
    fullyVisibleStart: 147,
    fadeOutStart: 321,
    hiddenAt: 336,
  },
  {
    text: "ترامب لفوكس نيوز: ينبغي أن نتقاضى مقابلا على حراسة المضيق وعندما نقوم بحراسته سنحصل على تعويض",
    fadeInStart: 350,
    fullyVisibleStart: 363,
    fadeOutStart: 609,
    hiddenAt: 616,
  },
];

const CANVAS_WIDTH = 1080;
const CANVAS_HEIGHT = 1440;

// ─── Quote opacity helper ─────────────────────────────────────────────────────

const computeQuoteOpacity = (
  frame: number,
  quote: RasdQuoteItem,
  durationInFrames: number,
): number => {
  const fadeInLen = quote.fullyVisibleStart - quote.fadeInStart;
  const input: number[] = [];
  const output: number[] = [];

  if (fadeInLen > 0) {
    input.push(quote.fadeInStart);
    output.push(0);
  }
  input.push(quote.fullyVisibleStart);
  output.push(1);
  input.push(quote.fadeOutStart);
  output.push(1);
  input.push(quote.hiddenAt);
  output.push(0);

  const base = interpolate(frame, input, output, {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  if (quote.loopFadeInStart != null && frame >= quote.loopFadeInStart) {
    return interpolate(
      frame,
      [quote.loopFadeInStart, durationInFrames],
      [0, 1],
      { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
    );
  }

  return base;
};

// ─── Font-family resolver ─────────────────────────────────────────────────────

/**
 * Resolves a font_family value from the template JSON to a CSS font-family name.
 * - If it's a URL (http/https) or a local path, we strip to the base filename
 *   and use a predictably named family (requires that font to be registered with loadFont).
 * - If it already looks like a family name (no slash, no dot), use as-is.
 *
 * For production, map known font filenames to their loaded CSS family names here.
 */
function resolveFontFamily(fontFamily?: string): string {
  if (!fontFamily) return "GhroobArabic";
  // URL or path → extract filename stem
  const filename = fontFamily.split("/").pop() ?? fontFamily;
  const stem = filename.replace(/\.[^.]+$/, "").toLowerCase();

  // Map known font files to their registered CSS family
  if (stem.includes("ghroob")) return "GhroobArabic";

  // Fallback: use the value as-is (works if it's already a CSS family name)
  return fontFamily;
}

// ─── Layer position helpers ───────────────────────────────────────────────────

/**
 * Computes the CSS `left` position of a text box given the layer config.
 * The layer's `x` is the CENTER of the text box (same as news_image_lib).
 * left = x - width/2
 */
function layerLeft(layer: TextLayerConfig): number {
  return layer.x - layer.width / 2;
}

// ─── Background template image ────────────────────────────────────────────────
export const TemplateBackground: React.FC<{ src: string }> = ({ src }) => {
  const imageSrc = src.startsWith("http") ? src : staticFile(src);
  return (
    <Img
      src={imageSrc}
      style={{
        position: "absolute",
        top: 0,
        left: 0,
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        objectFit: "cover",
      }}
    />
  );
};

// ─── Photo layer (upper media area) ──────────────────────────────────────────
export const PhotoLayer: React.FC<{ src: string; isVideo?: boolean }> = ({
  src,
  isVideo = false,
}) => {
  const resolvedSrc = src.startsWith("http") ? src : staticFile(src);

  // Photo area from the template JSON: x=0, y=-1, width=1080, height=860
  const photoStyle: React.CSSProperties = {
    position: "absolute",
    top: -1,
    left: 0,
    width: 1080,
    height: 860,
    objectFit: "cover",
    zIndex: 1,
  };

  if (isVideo) {
    return (
      <div
        style={{
          position: "absolute",
          top: -1,
          left: 0,
          width: 1080,
          height: 860,
          overflow: "hidden",
          zIndex: 1,
        }}
      >
        <OffthreadVideo
          src={resolvedSrc}
          style={{ width: "100%", height: "100%", objectFit: "cover" }}
        />
      </div>
    );
  }

  return <Img src={resolvedSrc} style={photoStyle} />;
};

// ─── Single fitted + justified text box ──────────────────────────────────────

/**
 * Renders a single text value (quote or source) inside a layer config box.
 * Uses `useArabicTextFit` to auto-size and justify exactly like news_image_lib.
 */
const FittedTextBox: React.FC<{
  text: string;
  layer: TextLayerConfig;
  opacity?: number;
}> = ({ text, layer, opacity = 1 }) => {
  const style = layer.style;
  const fontFamily = resolveFontFamily(style.font_family);
  const direction = style.direction ?? "rtl";
  const align = style.align ?? "right";
  const color = style.color ?? "#FFFFFF";
  const verticalAlign = style.vertical_align ?? "top";

  const { lines, fontSize, lineHeight } = useArabicTextFit({
    text,
    fontFamily,
    baseFontSize: style.base_font_size ?? 70,
    minFontSize: style.min_font_size ?? 40,
    availableWidth: layer.width,
    maxHeight: layer.max_height,
    lineSpacing: style.line_spacing ?? 1.2,
    useMetricsLineSpacing: style.use_metrics_line_spacing ?? false,
    kashida: style.kashida ?? false,
  });

  const totalTextHeight = lines.length * lineHeight;

  // Vertical alignment offset (mirrors layout_engine._calculate_text_position)
  let verticalOffset = 0;
  if (verticalAlign === "center") {
    verticalOffset = (layer.max_height - totalTextHeight) / 2;
  } else if (verticalAlign === "bottom") {
    verticalOffset = layer.max_height - totalTextHeight;
  }

  // Map CSS text-align from layer align value + direction
  const cssTextAlign: React.CSSProperties["textAlign"] =
    align === "center" ? "center" : direction === "rtl" ? "right" : "left";

  return (
    <div
      style={{
        position: "absolute",
        top: layer.y + verticalOffset,
        left: layerLeft(layer),
        width: layer.width,
        height: layer.max_height,
        overflow: "hidden",
        opacity,
        zIndex: 3,
      }}
    >
      {lines.map((line, i) => (
        <div
          key={i}
          style={{
            fontFamily,
            fontSize,
            lineHeight: `${lineHeight}px`,
            color,
            direction,
            textAlign: cssTextAlign,
            unicodeBidi: "plaintext",
            whiteSpace: "pre",
            height: lineHeight,
          }}
        >
          {line.text}
        </div>
      ))}
    </div>
  );
};

// ─── Quote container (cycles quotes with fades) ───────────────────────────────
export const QuoteContainer: React.FC<{
  quotes: RasdQuoteItem[];
  layer: TextLayerConfig;
}> = ({ quotes, layer }) => {
  const frame = useCurrentFrame();
  const { durationInFrames } = useVideoConfig();

  return (
    <>
      {quotes.map((quote, index) => (
        <FittedTextBox
          key={index}
          text={quote.text}
          layer={layer}
          opacity={computeQuoteOpacity(frame, quote, durationInFrames)}
        />
      ))}
    </>
  );
};

// ─── Source label ─────────────────────────────────────────────────────────────
export const SourceLabel: React.FC<{
  text: string;
  layer: TextLayerConfig;
}> = ({ text, layer }) => {
  return <FittedTextBox text={text} layer={layer} />;
};

// ─── Top-level composition ────────────────────────────────────────────────────
export const RasdNewsComposition: React.FC<RasdNewsProps> = ({
  photoSrc,
  photoIsVideo = false,
  backgroundImageSrc,
  quotes = DEFAULT_QUOTES,
  sourceText,
  newsTextLayer = DEFAULT_NEWS_TEXT_LAYER,
  sourceTextLayer = DEFAULT_SOURCE_TEXT_LAYER,
}) => {
  return (
    <AbsoluteFill
      style={{
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        backgroundColor: "#000000",
        overflow: "hidden",
      }}
    >
      {/* Background template image (panel, badge, etc. baked in) */}
      <div style={{ position: "absolute", inset: 0, zIndex: 0 }}>
        <TemplateBackground src={backgroundImageSrc} />
      </div>

      {/* Photo / video in the upper area */}
      <PhotoLayer src={photoSrc} isVideo={photoIsVideo} />

      {/* Cycling news headlines — font-fit + kashida applied per quote */}
      <QuoteContainer quotes={quotes} layer={newsTextLayer} />

      {/* Source label */}
      <SourceLabel text={sourceText} layer={sourceTextLayer} />
    </AbsoluteFill>
  );
};

// ─── Entry-point wrapper ──────────────────────────────────────────────────────
export const RasdNews: React.FC<Partial<RasdNewsProps>> = (props) => {
  return (
    <RasdNewsComposition
      photoSrc={props.photoSrc ?? "rasd/sample-photo.jpg"}
      photoIsVideo={props.photoIsVideo ?? false}
      backgroundImageSrc={props.backgroundImageSrc ?? "rasd/template-bg.png"}
      quotes={props.quotes ?? DEFAULT_QUOTES}
      sourceText={props.sourceText ?? "نص جديد"}
      newsTextLayer={props.newsTextLayer ?? DEFAULT_NEWS_TEXT_LAYER}
      sourceTextLayer={props.sourceTextLayer ?? DEFAULT_SOURCE_TEXT_LAYER}
    />
  );
};
